/* Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
*/

fn main() {
    let (mut a, mut b) = (1, 2);

    let mut temp: i32;
    let mut sum = 0;

    while b < 4000000 {
        temp = b;
        b = a + b;
        a = temp;

        // Add up even numbers
        if b % 2 == 0 {
            sum += b;
        }
    }

    print!("{}", sum);
}